// Code generated by ogen, DO NOT EDIT.

package api

// setDefaults set default value of fields.
func (s *ApiKeyInput) setDefaults() {
	{
		val := ApiKeyInputPermissions("full")
		s.Permissions.SetTo(val)
	}
}
