// Code generated by ogen, DO NOT EDIT.
package api

type AdminAssignDeviceRes interface {
	adminAssignDeviceRes()
}

type AdminCreateUserRes interface {
	adminCreateUserRes()
}

type AdminDeleteUserRes interface {
	adminDeleteUserRes()
}

type AdminDeleteUserSessionRes interface {
	adminDeleteUserSessionRes()
}

type AdminGetAuditLogRes interface {
	adminGetAuditLogRes()
}

type AdminGetStatisticsRes interface {
	adminGetStatisticsRes()
}

type AdminGetUserStatisticsRes interface {
	adminGetUserStatisticsRes()
}

type AdminListCalendarsRes interface {
	adminListCalendarsRes()
}

type AdminListDevicesRes interface {
	adminListDevicesRes()
}

type AdminListGeofencesRes interface {
	adminListGeofencesRes()
}

type AdminListNotificationsRes interface {
	adminListNotificationsRes()
}

type AdminListPositionsRes interface {
	adminListPositionsRes()
}

type AdminListUserDevicesRes interface {
	adminListUserDevicesRes()
}

type AdminListUserKeysRes interface {
	adminListUserKeysRes()
}

type AdminListUsersRes interface {
	adminListUsersRes()
}

type AdminStartSudoRes interface {
	adminStartSudoRes()
}

type AdminUnassignDeviceRes interface {
	adminUnassignDeviceRes()
}

type AdminUpdateUserRes interface {
	adminUpdateUserRes()
}

type CheckCalendarRes interface {
	checkCalendarRes()
}

type CreateApiKeyRes interface {
	createApiKeyRes()
}

type CreateCalendarRes interface {
	createCalendarRes()
}

type CreateCommandRes interface {
	createCommandRes()
}

type CreateDeviceRes interface {
	createDeviceRes()
}

type CreateGeofenceRes interface {
	createGeofenceRes()
}

type CreateNotificationRes interface {
	createNotificationRes()
}

type CreateShareRes interface {
	createShareRes()
}

type DeleteApiKeyRes interface {
	deleteApiKeyRes()
}

type DeleteCalendarRes interface {
	deleteCalendarRes()
}

type DeleteDeviceRes interface {
	deleteDeviceRes()
}

type DeleteGeofenceRes interface {
	deleteGeofenceRes()
}

type DeleteNotificationRes interface {
	deleteNotificationRes()
}

type DeletePasskeyRes interface {
	deletePasskeyRes()
}

type DeleteSessionRes interface {
	deleteSessionRes()
}

type DeleteShareRes interface {
	deleteShareRes()
}

type EndSudoRes interface {
	endSudoRes()
}

type GenerateTokenRes interface {
	generateTokenRes()
}

type GetCommandTypesRes interface {
	getCommandTypesRes()
}

type GetDeviceRes interface {
	getDeviceRes()
}

type GetGeofenceRes interface {
	getGeofenceRes()
}

type GetPositionsRes interface {
	getPositionsRes()
}

type GetSessionRes interface {
	getSessionRes()
}

type GetSharedDeviceRes interface {
	getSharedDeviceRes()
}

type GetSudoStatusRes interface {
	getSudoStatusRes()
}

type ImportGPXReq interface {
	importGPXReq()
}

type ImportGPXRes interface {
	importGPXRes()
}

type ListApiKeysRes interface {
	listApiKeysRes()
}

type ListCalendarsRes interface {
	listCalendarsRes()
}

type ListCommandsRes interface {
	listCommandsRes()
}

type ListDevicesRes interface {
	listDevicesRes()
}

type ListEventsRes interface {
	listEventsRes()
}

type ListGeofencesRes interface {
	listGeofencesRes()
}

type ListNotificationsRes interface {
	listNotificationsRes()
}

type ListPasskeysRes interface {
	listPasskeysRes()
}

type ListSessionsRes interface {
	listSessionsRes()
}

type ListSharesRes interface {
	listSharesRes()
}

type LoginReq interface {
	loginReq()
}

type LoginRes interface {
	loginRes()
}

type LogoutAllRes interface {
	logoutAllRes()
}

type LogoutRes interface {
	logoutRes()
}

type NotificationLogsRes interface {
	notificationLogsRes()
}

type OidcCallbackRes interface {
	oidcCallbackRes()
}

type PasskeyLoginBeginRes interface {
	passkeyLoginBeginRes()
}

type PasskeyLoginFinishRes interface {
	passkeyLoginFinishRes()
}

type PasskeyRegisterBeginRes interface {
	passkeyRegisterBeginRes()
}

type PasskeyRegisterFinishRes interface {
	passkeyRegisterFinishRes()
}

type ReportEventsRes interface {
	reportEventsRes()
}

type SendCommandRes interface {
	sendCommandRes()
}

type TestNotificationRes interface {
	testNotificationRes()
}

type UpdateCalendarRes interface {
	updateCalendarRes()
}

type UpdateDeviceRes interface {
	updateDeviceRes()
}

type UpdateGeofenceRes interface {
	updateGeofenceRes()
}

type UpdateNotificationRes interface {
	updateNotificationRes()
}

type UpdateProfileRes interface {
	updateProfileRes()
}
