// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AdminAssignDevice implements adminAssignDevice operation.
//
// Admin — assign a device to a user.
//
// POST /api/users/{id}/devices/{deviceId}
func (UnimplementedHandler) AdminAssignDevice(ctx context.Context, params AdminAssignDeviceParams) (r AdminAssignDeviceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AdminCreateUser implements adminCreateUser operation.
//
// Admin — create a user.
//
// POST /api/users
func (UnimplementedHandler) AdminCreateUser(ctx context.Context, req *UserInput) (r AdminCreateUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AdminDeleteUser implements adminDeleteUser operation.
//
// Admin — delete a user.
//
// DELETE /api/users/{id}
func (UnimplementedHandler) AdminDeleteUser(ctx context.Context, params AdminDeleteUserParams) (r AdminDeleteUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AdminDeleteUserSession implements adminDeleteUserSession operation.
//
// Admin — revoke a specific session for a user.
//
// DELETE /api/users/{id}/sessions/{sessionId}
func (UnimplementedHandler) AdminDeleteUserSession(ctx context.Context, params AdminDeleteUserSessionParams) (r AdminDeleteUserSessionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AdminGetAuditLog implements adminGetAuditLog operation.
//
// Admin — paginated audit log.
//
// GET /api/admin/audit
func (UnimplementedHandler) AdminGetAuditLog(ctx context.Context, params AdminGetAuditLogParams) (r AdminGetAuditLogRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AdminGetStatistics implements adminGetStatistics operation.
//
// Admin — platform-wide statistics.
//
// GET /api/admin/statistics
func (UnimplementedHandler) AdminGetStatistics(ctx context.Context) (r AdminGetStatisticsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AdminGetUserStatistics implements adminGetUserStatistics operation.
//
// Admin — statistics for a specific user.
//
// GET /api/admin/statistics/users/{id}
func (UnimplementedHandler) AdminGetUserStatistics(ctx context.Context, params AdminGetUserStatisticsParams) (r AdminGetUserStatisticsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AdminListCalendars implements adminListCalendars operation.
//
// Admin — list all calendars across all users.
//
// GET /api/admin/calendars
func (UnimplementedHandler) AdminListCalendars(ctx context.Context) (r AdminListCalendarsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AdminListDevices implements adminListDevices operation.
//
// Admin — list all devices across all users.
//
// GET /api/admin/devices
func (UnimplementedHandler) AdminListDevices(ctx context.Context) (r AdminListDevicesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AdminListGeofences implements adminListGeofences operation.
//
// Admin — list all geofences across all users.
//
// GET /api/admin/geofences
func (UnimplementedHandler) AdminListGeofences(ctx context.Context) (r AdminListGeofencesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AdminListNotifications implements adminListNotifications operation.
//
// Admin — list all notification rules across all users.
//
// GET /api/admin/notifications
func (UnimplementedHandler) AdminListNotifications(ctx context.Context) (r AdminListNotificationsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AdminListPositions implements adminListPositions operation.
//
// Admin — list all latest positions across all devices.
//
// GET /api/admin/positions
func (UnimplementedHandler) AdminListPositions(ctx context.Context) (r AdminListPositionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AdminListUserDevices implements adminListUserDevices operation.
//
// Admin — list all devices for a user.
//
// GET /api/users/{id}/devices
func (UnimplementedHandler) AdminListUserDevices(ctx context.Context, params AdminListUserDevicesParams) (r AdminListUserDevicesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AdminListUserKeys implements adminListUserKeys operation.
//
// Admin — list API keys for a user.
//
// GET /api/users/{id}/keys
func (UnimplementedHandler) AdminListUserKeys(ctx context.Context, params AdminListUserKeysParams) (r AdminListUserKeysRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AdminListUsers implements adminListUsers operation.
//
// Admin — list all users.
//
// GET /api/users
func (UnimplementedHandler) AdminListUsers(ctx context.Context) (r AdminListUsersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AdminStartSudo implements adminStartSudo operation.
//
// Admin — start impersonating a user.
//
// POST /api/admin/sudo/{id}
func (UnimplementedHandler) AdminStartSudo(ctx context.Context, params AdminStartSudoParams) (r AdminStartSudoRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AdminUnassignDevice implements adminUnassignDevice operation.
//
// Admin — unassign a device from a user.
//
// DELETE /api/users/{id}/devices/{deviceId}
func (UnimplementedHandler) AdminUnassignDevice(ctx context.Context, params AdminUnassignDeviceParams) (r AdminUnassignDeviceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AdminUpdateUser implements adminUpdateUser operation.
//
// Admin — update a user.
//
// PUT /api/users/{id}
func (UnimplementedHandler) AdminUpdateUser(ctx context.Context, req *UserInput, params AdminUpdateUserParams) (r AdminUpdateUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CheckCalendar implements checkCalendar operation.
//
// Check if a calendar is currently active.
//
// GET /api/calendars/{id}/check
func (UnimplementedHandler) CheckCalendar(ctx context.Context, params CheckCalendarParams) (r CheckCalendarRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateApiKey implements createApiKey operation.
//
// Create an API key.
//
// POST /api/keys
func (UnimplementedHandler) CreateApiKey(ctx context.Context, req *ApiKeyInput) (r CreateApiKeyRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateCalendar implements createCalendar operation.
//
// Create a calendar.
//
// POST /api/calendars
func (UnimplementedHandler) CreateCalendar(ctx context.Context, req *CalendarInput) (r CreateCalendarRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateCommand implements createCommand operation.
//
// Save a command (not yet sent).
//
// POST /api/commands
func (UnimplementedHandler) CreateCommand(ctx context.Context, req *CommandInput) (r CreateCommandRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateDevice implements createDevice operation.
//
// Create a device.
//
// POST /api/devices
func (UnimplementedHandler) CreateDevice(ctx context.Context, req *DeviceInput) (r CreateDeviceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateGeofence implements createGeofence operation.
//
// Create a geofence.
//
// POST /api/geofences
func (UnimplementedHandler) CreateGeofence(ctx context.Context, req *GeofenceInput) (r CreateGeofenceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateNotification implements createNotification operation.
//
// Create a notification rule.
//
// POST /api/notifications
func (UnimplementedHandler) CreateNotification(ctx context.Context, req *NotificationRuleInput) (r CreateNotificationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateShare implements createShare operation.
//
// Create a public share link for a device.
//
// POST /api/devices/{id}/share
func (UnimplementedHandler) CreateShare(ctx context.Context, req OptCreateShareRequest, params CreateShareParams) (r CreateShareRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteApiKey implements deleteApiKey operation.
//
// Delete an API key.
//
// DELETE /api/keys/{id}
func (UnimplementedHandler) DeleteApiKey(ctx context.Context, params DeleteApiKeyParams) (r DeleteApiKeyRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteCalendar implements deleteCalendar operation.
//
// Delete a calendar.
//
// DELETE /api/calendars/{id}
func (UnimplementedHandler) DeleteCalendar(ctx context.Context, params DeleteCalendarParams) (r DeleteCalendarRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteDevice implements deleteDevice operation.
//
// Delete a device.
//
// DELETE /api/devices/{id}
func (UnimplementedHandler) DeleteDevice(ctx context.Context, params DeleteDeviceParams) (r DeleteDeviceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteGeofence implements deleteGeofence operation.
//
// Delete a geofence.
//
// DELETE /api/geofences/{id}
func (UnimplementedHandler) DeleteGeofence(ctx context.Context, params DeleteGeofenceParams) (r DeleteGeofenceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteNotification implements deleteNotification operation.
//
// Delete a notification rule.
//
// DELETE /api/notifications/{id}
func (UnimplementedHandler) DeleteNotification(ctx context.Context, params DeleteNotificationParams) (r DeleteNotificationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteSession implements deleteSession operation.
//
// Revoke a specific session.
//
// DELETE /api/sessions/{id}
func (UnimplementedHandler) DeleteSession(ctx context.Context, params DeleteSessionParams) (r DeleteSessionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteShare implements deleteShare operation.
//
// Delete a share link.
//
// DELETE /api/shares/{id}
func (UnimplementedHandler) DeleteShare(ctx context.Context, params DeleteShareParams) (r DeleteShareRes, _ error) {
	return r, ht.ErrNotImplemented
}

// EndSudo implements endSudo operation.
//
// End sudo/impersonation session.
//
// DELETE /api/admin/sudo
func (UnimplementedHandler) EndSudo(ctx context.Context) (r EndSudoRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GenerateToken implements generateToken operation.
//
// Generate a long-lived API token for the current session.
//
// POST /api/session/token
func (UnimplementedHandler) GenerateToken(ctx context.Context) (r GenerateTokenRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCommandTypes implements getCommandTypes operation.
//
// List supported command types.
//
// GET /api/commands/types
func (UnimplementedHandler) GetCommandTypes(ctx context.Context) (r GetCommandTypesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDevice implements getDevice operation.
//
// Get a device by ID.
//
// GET /api/devices/{id}
func (UnimplementedHandler) GetDevice(ctx context.Context, params GetDeviceParams) (r GetDeviceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetGeofence implements getGeofence operation.
//
// Get a geofence by ID.
//
// GET /api/geofences/{id}
func (UnimplementedHandler) GetGeofence(ctx context.Context, params GetGeofenceParams) (r GetGeofenceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetHealth implements getHealth operation.
//
// Health check.
//
// GET /api/health
func (UnimplementedHandler) GetHealth(ctx context.Context) (r *GetHealthOK, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOIDCConfig implements getOIDCConfig operation.
//
// Get OIDC configuration (enabled/disabled).
//
// GET /api/auth/oidc/config
func (UnimplementedHandler) GetOIDCConfig(ctx context.Context) (r *OIDCConfig, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPositions implements getPositions operation.
//
// Get positions for devices.
//
// GET /api/positions
func (UnimplementedHandler) GetPositions(ctx context.Context, params GetPositionsParams) (r GetPositionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetServer implements getServer operation.
//
// Traccar-compatible server info.
//
// GET /api/server
func (UnimplementedHandler) GetServer(ctx context.Context) (r *ServerInfo, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSession implements getSession operation.
//
// Get current session / validate credentials.
//
// GET /api/session
func (UnimplementedHandler) GetSession(ctx context.Context) (r GetSessionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSharedDevice implements getSharedDevice operation.
//
// Get device info via public share token.
//
// GET /api/share/{token}
func (UnimplementedHandler) GetSharedDevice(ctx context.Context, params GetSharedDeviceParams) (r GetSharedDeviceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSudoStatus implements getSudoStatus operation.
//
// Get current sudo/impersonation status.
//
// GET /api/admin/sudo
func (UnimplementedHandler) GetSudoStatus(ctx context.Context) (r GetSudoStatusRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetVersion implements getVersion operation.
//
// Version info.
//
// GET /api/version
func (UnimplementedHandler) GetVersion(ctx context.Context) (r *VersionInfo, _ error) {
	return r, ht.ErrNotImplemented
}

// ImportGPX implements importGPX operation.
//
// Import GPX track for a device.
//
// POST /api/devices/{id}/gpx
func (UnimplementedHandler) ImportGPX(ctx context.Context, req ImportGPXReq, params ImportGPXParams) (r ImportGPXRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListApiKeys implements listApiKeys operation.
//
// List API keys for the authenticated user.
//
// GET /api/keys
func (UnimplementedHandler) ListApiKeys(ctx context.Context) (r ListApiKeysRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListCalendars implements listCalendars operation.
//
// List calendars for the authenticated user.
//
// GET /api/calendars
func (UnimplementedHandler) ListCalendars(ctx context.Context) (r ListCalendarsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListCommands implements listCommands operation.
//
// List saved commands.
//
// GET /api/commands
func (UnimplementedHandler) ListCommands(ctx context.Context, params ListCommandsParams) (r ListCommandsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListDevices implements listDevices operation.
//
// List devices for the authenticated user.
//
// GET /api/devices
func (UnimplementedHandler) ListDevices(ctx context.Context) (r ListDevicesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListEvents implements listEvents operation.
//
// List events for the authenticated user's devices.
//
// GET /api/events
func (UnimplementedHandler) ListEvents(ctx context.Context, params ListEventsParams) (r ListEventsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListGeofences implements listGeofences operation.
//
// List geofences for the authenticated user.
//
// GET /api/geofences
func (UnimplementedHandler) ListGeofences(ctx context.Context) (r ListGeofencesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListNotifications implements listNotifications operation.
//
// List notification rules for the authenticated user.
//
// GET /api/notifications
func (UnimplementedHandler) ListNotifications(ctx context.Context) (r ListNotificationsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListSessions implements listSessions operation.
//
// List active sessions for the authenticated user.
//
// GET /api/sessions
func (UnimplementedHandler) ListSessions(ctx context.Context) (r ListSessionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListShares implements listShares operation.
//
// List share links for a device.
//
// GET /api/devices/{id}/shares
func (UnimplementedHandler) ListShares(ctx context.Context, params ListSharesParams) (r ListSharesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Login implements login operation.
//
// Login with email + password.
//
// POST /api/session
func (UnimplementedHandler) Login(ctx context.Context, req *LoginRequest) (r LoginRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Logout implements logout operation.
//
// Logout (delete current session).
//
// DELETE /api/session
func (UnimplementedHandler) Logout(ctx context.Context) (r LogoutRes, _ error) {
	return r, ht.ErrNotImplemented
}

// LogoutAll implements logoutAll operation.
//
// Revoke all sessions for the authenticated user.
//
// DELETE /api/sessions
func (UnimplementedHandler) LogoutAll(ctx context.Context) (r LogoutAllRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NotificationLogs implements notificationLogs operation.
//
// Get delivery logs for a notification rule.
//
// GET /api/notifications/{id}/logs
func (UnimplementedHandler) NotificationLogs(ctx context.Context, params NotificationLogsParams) (r NotificationLogsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// OidcCallback implements oidcCallback operation.
//
// OIDC callback after provider authentication.
//
// GET /api/auth/oidc/callback
func (UnimplementedHandler) OidcCallback(ctx context.Context, params OidcCallbackParams) (r OidcCallbackRes, _ error) {
	return r, ht.ErrNotImplemented
}

// OidcLogin implements oidcLogin operation.
//
// Initiate OIDC login flow (redirects to provider).
//
// GET /api/auth/oidc/login
func (UnimplementedHandler) OidcLogin(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// ReportEvents implements reportEvents operation.
//
// Report events in a time range (same as listEvents, Traccar-compatible path).
//
// GET /api/reports/events
func (UnimplementedHandler) ReportEvents(ctx context.Context, params ReportEventsParams) (r ReportEventsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SendCommand implements sendCommand operation.
//
// Send a command to a device immediately.
//
// POST /api/commands/send
func (UnimplementedHandler) SendCommand(ctx context.Context, req *SendCommandRequest) (r SendCommandRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TestNotification implements testNotification operation.
//
// Send a test notification.
//
// POST /api/notifications/{id}/test
func (UnimplementedHandler) TestNotification(ctx context.Context, params TestNotificationParams) (r TestNotificationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateCalendar implements updateCalendar operation.
//
// Update a calendar.
//
// PUT /api/calendars/{id}
func (UnimplementedHandler) UpdateCalendar(ctx context.Context, req *CalendarInput, params UpdateCalendarParams) (r UpdateCalendarRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateDevice implements updateDevice operation.
//
// Update a device.
//
// PUT /api/devices/{id}
func (UnimplementedHandler) UpdateDevice(ctx context.Context, req *DeviceInput, params UpdateDeviceParams) (r UpdateDeviceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateGeofence implements updateGeofence operation.
//
// Update a geofence.
//
// PUT /api/geofences/{id}
func (UnimplementedHandler) UpdateGeofence(ctx context.Context, req *GeofenceUpdateInput, params UpdateGeofenceParams) (r UpdateGeofenceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateNotification implements updateNotification operation.
//
// Update a notification rule.
//
// PUT /api/notifications/{id}
func (UnimplementedHandler) UpdateNotification(ctx context.Context, req *NotificationRuleInput, params UpdateNotificationParams) (r UpdateNotificationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateProfile implements updateProfile operation.
//
// Update the authenticated user's own profile.
//
// PUT /api/profile
func (UnimplementedHandler) UpdateProfile(ctx context.Context, req *UpdateProfileRequest) (r UpdateProfileRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *UnexpectedErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *UnexpectedErrorStatusCode) {
	r = new(UnexpectedErrorStatusCode)
	return r
}
