// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"
	"strings"

	"github.com/ogen-go/ogen/uri"
)

var (
	rn10AllowedHeaders = map[string]string{
		"GET": "Authorization,X-Auth-Token",
	}
	rn15AllowedHeaders = map[string]string{
		"GET": "Authorization,X-Auth-Token",
	}
	rn16AllowedHeaders = map[string]string{
		"GET": "Authorization,X-Auth-Token",
	}
	rn17AllowedHeaders = map[string]string{
		"GET": "Authorization,X-Auth-Token",
	}
	rn18AllowedHeaders = map[string]string{
		"GET": "Authorization,X-Auth-Token",
	}
	rn19AllowedHeaders = map[string]string{
		"GET": "Authorization,X-Auth-Token",
	}
	rn12AllowedHeaders = map[string]string{
		"GET": "Authorization,X-Auth-Token",
	}
	rn14AllowedHeaders = map[string]string{
		"GET": "Authorization,X-Auth-Token",
	}
	rn49AllowedHeaders = map[string]string{
		"DELETE": "Authorization,X-Auth-Token",
		"GET":    "Authorization,X-Auth-Token",
	}
	rn24AllowedHeaders = map[string]string{
		"POST": "Authorization,X-Auth-Token",
	}
	rn29AllowedHeaders = map[string]string{
		"GET":  "Authorization,X-Auth-Token",
		"POST": "Authorization,Content-Type,X-Auth-Token",
	}
	rn26AllowedHeaders = map[string]string{
		"DELETE": "Authorization,X-Auth-Token",
		"PUT":    "Authorization,Content-Type,X-Auth-Token",
	}
	rn27AllowedHeaders = map[string]string{
		"GET": "Authorization,X-Auth-Token",
	}
	rn31AllowedHeaders = map[string]string{
		"GET":  "Authorization,X-Auth-Token",
		"POST": "Authorization,Content-Type,X-Auth-Token",
	}
	rn75AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type,X-Auth-Token",
	}
	rn52AllowedHeaders = map[string]string{
		"GET": "Authorization,X-Auth-Token",
	}
	rn32AllowedHeaders = map[string]string{
		"GET":  "Authorization,X-Auth-Token",
		"POST": "Authorization,Content-Type,X-Auth-Token",
	}
	rn36AllowedHeaders = map[string]string{
		"DELETE": "Authorization,X-Auth-Token",
		"GET":    "Authorization,X-Auth-Token",
		"PUT":    "Authorization,Content-Type,X-Auth-Token",
	}
	rn64AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type,X-Auth-Token",
	}
	rn37AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type,X-Auth-Token",
	}
	rn67AllowedHeaders = map[string]string{
		"GET": "Authorization,X-Auth-Token",
	}
	rn65AllowedHeaders = map[string]string{
		"GET": "Authorization,X-Auth-Token",
	}
	rn33AllowedHeaders = map[string]string{
		"GET":  "Authorization,X-Auth-Token",
		"POST": "Authorization,Content-Type,X-Auth-Token",
	}
	rn41AllowedHeaders = map[string]string{
		"DELETE": "Authorization,X-Auth-Token",
		"GET":    "Authorization,X-Auth-Token",
		"PUT":    "Authorization,Content-Type,X-Auth-Token",
	}
	rn28AllowedHeaders = map[string]string{
		"GET":  "Authorization,X-Auth-Token",
		"POST": "Authorization,Content-Type,X-Auth-Token",
	}
	rn39AllowedHeaders = map[string]string{
		"DELETE": "Authorization,X-Auth-Token",
	}
	rn34AllowedHeaders = map[string]string{
		"GET":  "Authorization,X-Auth-Token",
		"POST": "Authorization,Content-Type,X-Auth-Token",
	}
	rn43AllowedHeaders = map[string]string{
		"DELETE": "Authorization,X-Auth-Token",
		"PUT":    "Authorization,Content-Type,X-Auth-Token",
	}
	rn68AllowedHeaders = map[string]string{
		"GET": "Authorization,X-Auth-Token",
	}
	rn77AllowedHeaders = map[string]string{
		"POST": "Authorization,X-Auth-Token",
	}
	rn56AllowedHeaders = map[string]string{
		"GET": "Authorization,X-Auth-Token",
	}
	rn79AllowedHeaders = map[string]string{
		"PUT": "Authorization,Content-Type,X-Auth-Token",
	}
	rn73AllowedHeaders = map[string]string{
		"GET": "Authorization,X-Auth-Token",
	}
	rn50AllowedHeaders = map[string]string{
		"DELETE": "Authorization,X-Auth-Token",
		"GET":    "Authorization,X-Auth-Token",
		"POST":   "Content-Type",
	}
	rn51AllowedHeaders = map[string]string{
		"POST": "Authorization,X-Auth-Token",
	}
	rn66AllowedHeaders = map[string]string{
		"DELETE": "Authorization,X-Auth-Token",
		"GET":    "Authorization,X-Auth-Token",
	}
	rn45AllowedHeaders = map[string]string{
		"DELETE": "Authorization,X-Auth-Token",
	}
	rn48AllowedHeaders = map[string]string{
		"DELETE": "Authorization,X-Auth-Token",
	}
	rn5AllowedHeaders = map[string]string{
		"GET":  "Authorization,X-Auth-Token",
		"POST": "Authorization,Content-Type,X-Auth-Token",
	}
	rn2AllowedHeaders = map[string]string{
		"DELETE": "Authorization,X-Auth-Token",
		"PUT":    "Authorization,Content-Type,X-Auth-Token",
	}
	rn20AllowedHeaders = map[string]string{
		"GET": "Authorization,X-Auth-Token",
	}
	rn4AllowedHeaders = map[string]string{
		"DELETE": "Authorization,X-Auth-Token",
		"POST":   "Authorization,X-Auth-Token",
	}
	rn21AllowedHeaders = map[string]string{
		"GET": "Authorization,X-Auth-Token",
	}
	rn8AllowedHeaders = map[string]string{
		"DELETE": "Authorization,X-Auth-Token",
	}
)

func (s *Server) cutPrefix(path string) (string, bool) {
	prefix := s.cfg.Prefix
	if prefix == "" {
		return path, true
	}
	if !strings.HasPrefix(path, prefix) {
		// Prefix doesn't match.
		return "", false
	}
	// Cut prefix from the path.
	return strings.TrimPrefix(path, prefix), true
}

// ServeHTTP serves http request as defined by OpenAPI v3 specification,
// calling handler that matches the path or returning not found error.
func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	elem := r.URL.Path
	elemIsEscaped := false
	if rawPath := r.URL.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
			elemIsEscaped = strings.ContainsRune(elem, '%')
		}
	}

	elem, ok := s.cutPrefix(elem)
	if !ok || len(elem) == 0 {
		s.notFound(w, r)
		return
	}
	args := [2]string{}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/api/"

			if l := len("/api/"); len(elem) >= l && elem[0:l] == "/api/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'a': // Prefix: "a"

				if l := len("a"); len(elem) >= l && elem[0:l] == "a" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'd': // Prefix: "dmin/"

					if l := len("dmin/"); len(elem) >= l && elem[0:l] == "dmin/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'a': // Prefix: "audit"

						if l := len("audit"); len(elem) >= l && elem[0:l] == "audit" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleAdminGetAuditLogRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET",
									allowedHeaders: rn10AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

					case 'c': // Prefix: "calendars"

						if l := len("calendars"); len(elem) >= l && elem[0:l] == "calendars" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleAdminListCalendarsRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET",
									allowedHeaders: rn15AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

					case 'd': // Prefix: "devices"

						if l := len("devices"); len(elem) >= l && elem[0:l] == "devices" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleAdminListDevicesRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET",
									allowedHeaders: rn16AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

					case 'g': // Prefix: "geofences"

						if l := len("geofences"); len(elem) >= l && elem[0:l] == "geofences" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleAdminListGeofencesRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET",
									allowedHeaders: rn17AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

					case 'n': // Prefix: "notifications"

						if l := len("notifications"); len(elem) >= l && elem[0:l] == "notifications" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleAdminListNotificationsRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET",
									allowedHeaders: rn18AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

					case 'p': // Prefix: "positions"

						if l := len("positions"); len(elem) >= l && elem[0:l] == "positions" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleAdminListPositionsRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET",
									allowedHeaders: rn19AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

					case 's': // Prefix: "s"

						if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 't': // Prefix: "tatistics"

							if l := len("tatistics"); len(elem) >= l && elem[0:l] == "tatistics" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch r.Method {
								case "GET":
									s.handleAdminGetStatisticsRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: rn12AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}
							switch elem[0] {
							case '/': // Prefix: "/users/"

								if l := len("/users/"); len(elem) >= l && elem[0:l] == "/users/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "id"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[0] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "GET":
										s.handleAdminGetUserStatisticsRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "GET",
											allowedHeaders: rn14AllowedHeaders,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}

							}

						case 'u': // Prefix: "udo"

							if l := len("udo"); len(elem) >= l && elem[0:l] == "udo" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch r.Method {
								case "DELETE":
									s.handleEndSudoRequest([0]string{}, elemIsEscaped, w, r)
								case "GET":
									s.handleGetSudoStatusRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "DELETE,GET",
										allowedHeaders: rn49AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "id"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[0] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "POST":
										s.handleAdminStartSudoRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "POST",
											allowedHeaders: rn24AllowedHeaders,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}

							}

						}

					}

				case 'u': // Prefix: "uth/oidc/"

					if l := len("uth/oidc/"); len(elem) >= l && elem[0:l] == "uth/oidc/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'c': // Prefix: "c"

						if l := len("c"); len(elem) >= l && elem[0:l] == "c" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'a': // Prefix: "allback"

							if l := len("allback"); len(elem) >= l && elem[0:l] == "allback" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleOidcCallbackRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: nil,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						case 'o': // Prefix: "onfig"

							if l := len("onfig"); len(elem) >= l && elem[0:l] == "onfig" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleGetOIDCConfigRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: nil,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						}

					case 'l': // Prefix: "login"

						if l := len("login"); len(elem) >= l && elem[0:l] == "login" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleOidcLoginRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET",
									allowedHeaders: nil,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

					}

				}

			case 'c': // Prefix: "c"

				if l := len("c"); len(elem) >= l && elem[0:l] == "c" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'a': // Prefix: "alendars"

					if l := len("alendars"); len(elem) >= l && elem[0:l] == "alendars" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch r.Method {
						case "GET":
							s.handleListCalendarsRequest([0]string{}, elemIsEscaped, w, r)
						case "POST":
							s.handleCreateCalendarRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET,POST",
								allowedHeaders: rn29AllowedHeaders,
								acceptPost:     "application/json",
								acceptPatch:    "",
							})
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "id"
						// Match until "/"
						idx := strings.IndexByte(elem, '/')
						if idx < 0 {
							idx = len(elem)
						}
						args[0] = elem[:idx]
						elem = elem[idx:]

						if len(elem) == 0 {
							switch r.Method {
							case "DELETE":
								s.handleDeleteCalendarRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							case "PUT":
								s.handleUpdateCalendarRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "DELETE,PUT",
									allowedHeaders: rn26AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}
						switch elem[0] {
						case '/': // Prefix: "/check"

							if l := len("/check"); len(elem) >= l && elem[0:l] == "/check" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleCheckCalendarRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: rn27AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						}

					}

				case 'o': // Prefix: "ommands"

					if l := len("ommands"); len(elem) >= l && elem[0:l] == "ommands" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch r.Method {
						case "GET":
							s.handleListCommandsRequest([0]string{}, elemIsEscaped, w, r)
						case "POST":
							s.handleCreateCommandRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET,POST",
								allowedHeaders: rn31AllowedHeaders,
								acceptPost:     "application/json",
								acceptPatch:    "",
							})
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 's': // Prefix: "send"

							if l := len("send"); len(elem) >= l && elem[0:l] == "send" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleSendCommandRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "POST",
										allowedHeaders: rn75AllowedHeaders,
										acceptPost:     "application/json",
										acceptPatch:    "",
									})
								}

								return
							}

						case 't': // Prefix: "types"

							if l := len("types"); len(elem) >= l && elem[0:l] == "types" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleGetCommandTypesRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: rn52AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						}

					}

				}

			case 'd': // Prefix: "devices"

				if l := len("devices"); len(elem) >= l && elem[0:l] == "devices" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "GET":
						s.handleListDevicesRequest([0]string{}, elemIsEscaped, w, r)
					case "POST":
						s.handleCreateDeviceRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET,POST",
							allowedHeaders: rn32AllowedHeaders,
							acceptPost:     "application/json",
							acceptPatch:    "",
						})
					}

					return
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "id"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch r.Method {
						case "DELETE":
							s.handleDeleteDeviceRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "GET":
							s.handleGetDeviceRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "PUT":
							s.handleUpdateDeviceRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "DELETE,GET,PUT",
								allowedHeaders: rn36AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'g': // Prefix: "gpx"

							if l := len("gpx"); len(elem) >= l && elem[0:l] == "gpx" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleImportGPXRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "POST",
										allowedHeaders: rn64AllowedHeaders,
										acceptPost:     "application/gpx+xml,multipart/form-data",
										acceptPatch:    "",
									})
								}

								return
							}

						case 's': // Prefix: "share"

							if l := len("share"); len(elem) >= l && elem[0:l] == "share" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch r.Method {
								case "POST":
									s.handleCreateShareRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "POST",
										allowedHeaders: rn37AllowedHeaders,
										acceptPost:     "application/json",
										acceptPatch:    "",
									})
								}

								return
							}
							switch elem[0] {
							case 's': // Prefix: "s"

								if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "GET":
										s.handleListSharesRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "GET",
											allowedHeaders: rn67AllowedHeaders,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}

							}

						}

					}

				}

			case 'e': // Prefix: "events"

				if l := len("events"); len(elem) >= l && elem[0:l] == "events" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "GET":
						s.handleListEventsRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET",
							allowedHeaders: rn65AllowedHeaders,
							acceptPost:     "",
							acceptPatch:    "",
						})
					}

					return
				}

			case 'g': // Prefix: "geofences"

				if l := len("geofences"); len(elem) >= l && elem[0:l] == "geofences" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "GET":
						s.handleListGeofencesRequest([0]string{}, elemIsEscaped, w, r)
					case "POST":
						s.handleCreateGeofenceRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET,POST",
							allowedHeaders: rn33AllowedHeaders,
							acceptPost:     "application/json",
							acceptPatch:    "",
						})
					}

					return
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "id"
					// Leaf parameter, slashes are prohibited
					idx := strings.IndexByte(elem, '/')
					if idx >= 0 {
						break
					}
					args[0] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "DELETE":
							s.handleDeleteGeofenceRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "GET":
							s.handleGetGeofenceRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "PUT":
							s.handleUpdateGeofenceRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "DELETE,GET,PUT",
								allowedHeaders: rn41AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}

				}

			case 'h': // Prefix: "health"

				if l := len("health"); len(elem) >= l && elem[0:l] == "health" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "GET":
						s.handleGetHealthRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET",
							allowedHeaders: nil,
							acceptPost:     "",
							acceptPatch:    "",
						})
					}

					return
				}

			case 'k': // Prefix: "keys"

				if l := len("keys"); len(elem) >= l && elem[0:l] == "keys" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "GET":
						s.handleListApiKeysRequest([0]string{}, elemIsEscaped, w, r)
					case "POST":
						s.handleCreateApiKeyRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET,POST",
							allowedHeaders: rn28AllowedHeaders,
							acceptPost:     "application/json",
							acceptPatch:    "",
						})
					}

					return
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "id"
					// Leaf parameter, slashes are prohibited
					idx := strings.IndexByte(elem, '/')
					if idx >= 0 {
						break
					}
					args[0] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "DELETE":
							s.handleDeleteApiKeyRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "DELETE",
								allowedHeaders: rn39AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}

				}

			case 'n': // Prefix: "notifications"

				if l := len("notifications"); len(elem) >= l && elem[0:l] == "notifications" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "GET":
						s.handleListNotificationsRequest([0]string{}, elemIsEscaped, w, r)
					case "POST":
						s.handleCreateNotificationRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET,POST",
							allowedHeaders: rn34AllowedHeaders,
							acceptPost:     "application/json",
							acceptPatch:    "",
						})
					}

					return
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "id"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch r.Method {
						case "DELETE":
							s.handleDeleteNotificationRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "PUT":
							s.handleUpdateNotificationRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "DELETE,PUT",
								allowedHeaders: rn43AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'l': // Prefix: "logs"

							if l := len("logs"); len(elem) >= l && elem[0:l] == "logs" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleNotificationLogsRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: rn68AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						case 't': // Prefix: "test"

							if l := len("test"); len(elem) >= l && elem[0:l] == "test" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleTestNotificationRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "POST",
										allowedHeaders: rn77AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						}

					}

				}

			case 'p': // Prefix: "p"

				if l := len("p"); len(elem) >= l && elem[0:l] == "p" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'o': // Prefix: "ositions"

					if l := len("ositions"); len(elem) >= l && elem[0:l] == "ositions" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleGetPositionsRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET",
								allowedHeaders: rn56AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}

				case 'r': // Prefix: "rofile"

					if l := len("rofile"); len(elem) >= l && elem[0:l] == "rofile" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "PUT":
							s.handleUpdateProfileRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "PUT",
								allowedHeaders: rn79AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}

				}

			case 'r': // Prefix: "reports/events"

				if l := len("reports/events"); len(elem) >= l && elem[0:l] == "reports/events" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "GET":
						s.handleReportEventsRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET",
							allowedHeaders: rn73AllowedHeaders,
							acceptPost:     "",
							acceptPatch:    "",
						})
					}

					return
				}

			case 's': // Prefix: "s"

				if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'e': // Prefix: "e"

					if l := len("e"); len(elem) >= l && elem[0:l] == "e" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'r': // Prefix: "rver"

						if l := len("rver"); len(elem) >= l && elem[0:l] == "rver" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleGetServerRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET",
									allowedHeaders: nil,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

					case 's': // Prefix: "ssion"

						if l := len("ssion"); len(elem) >= l && elem[0:l] == "ssion" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch r.Method {
							case "DELETE":
								s.handleLogoutRequest([0]string{}, elemIsEscaped, w, r)
							case "GET":
								s.handleGetSessionRequest([0]string{}, elemIsEscaped, w, r)
							case "POST":
								s.handleLoginRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "DELETE,GET,POST",
									allowedHeaders: rn50AllowedHeaders,
									acceptPost:     "application/json,application/x-www-form-urlencoded",
									acceptPatch:    "",
								})
							}

							return
						}
						switch elem[0] {
						case '/': // Prefix: "/token"

							if l := len("/token"); len(elem) >= l && elem[0:l] == "/token" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleGenerateTokenRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "POST",
										allowedHeaders: rn51AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						case 's': // Prefix: "s"

							if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch r.Method {
								case "DELETE":
									s.handleLogoutAllRequest([0]string{}, elemIsEscaped, w, r)
								case "GET":
									s.handleListSessionsRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "DELETE,GET",
										allowedHeaders: rn66AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "id"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[0] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "DELETE":
										s.handleDeleteSessionRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "DELETE",
											allowedHeaders: rn45AllowedHeaders,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}

							}

						}

					}

				case 'h': // Prefix: "hare"

					if l := len("hare"); len(elem) >= l && elem[0:l] == "hare" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "token"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[0] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleGetSharedDeviceRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET",
									allowedHeaders: nil,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

					case 's': // Prefix: "s/"

						if l := len("s/"); len(elem) >= l && elem[0:l] == "s/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "id"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[0] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "DELETE":
								s.handleDeleteShareRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "DELETE",
									allowedHeaders: rn48AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

					}

				}

			case 'u': // Prefix: "users"

				if l := len("users"); len(elem) >= l && elem[0:l] == "users" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "GET":
						s.handleAdminListUsersRequest([0]string{}, elemIsEscaped, w, r)
					case "POST":
						s.handleAdminCreateUserRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET,POST",
							allowedHeaders: rn5AllowedHeaders,
							acceptPost:     "application/json",
							acceptPatch:    "",
						})
					}

					return
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "id"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch r.Method {
						case "DELETE":
							s.handleAdminDeleteUserRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "PUT":
							s.handleAdminUpdateUserRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "DELETE,PUT",
								allowedHeaders: rn2AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'd': // Prefix: "devices"

							if l := len("devices"); len(elem) >= l && elem[0:l] == "devices" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch r.Method {
								case "GET":
									s.handleAdminListUserDevicesRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: rn20AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "deviceId"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[1] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "DELETE":
										s.handleAdminUnassignDeviceRequest([2]string{
											args[0],
											args[1],
										}, elemIsEscaped, w, r)
									case "POST":
										s.handleAdminAssignDeviceRequest([2]string{
											args[0],
											args[1],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "DELETE,POST",
											allowedHeaders: rn4AllowedHeaders,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}

							}

						case 'k': // Prefix: "keys"

							if l := len("keys"); len(elem) >= l && elem[0:l] == "keys" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleAdminListUserKeysRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: rn21AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						case 's': // Prefix: "sessions/"

							if l := len("sessions/"); len(elem) >= l && elem[0:l] == "sessions/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "sessionId"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[1] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "DELETE":
									s.handleAdminDeleteUserSessionRequest([2]string{
										args[0],
										args[1],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "DELETE",
										allowedHeaders: rn8AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						}

					}

				}

			case 'v': // Prefix: "version"

				if l := len("version"); len(elem) >= l && elem[0:l] == "version" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "GET":
						s.handleGetVersionRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET",
							allowedHeaders: nil,
							acceptPost:     "",
							acceptPatch:    "",
						})
					}

					return
				}

			}

		}
	}
	s.notFound(w, r)
}

// Route is route object.
type Route struct {
	name           string
	summary        string
	operationID    string
	operationGroup string
	pathPattern    string
	count          int
	args           [2]string
}

// Name returns ogen operation name.
//
// It is guaranteed to be unique and not empty.
func (r Route) Name() string {
	return r.name
}

// Summary returns OpenAPI summary.
func (r Route) Summary() string {
	return r.summary
}

// OperationID returns OpenAPI operationId.
func (r Route) OperationID() string {
	return r.operationID
}

// OperationGroup returns the x-ogen-operation-group value.
func (r Route) OperationGroup() string {
	return r.operationGroup
}

// PathPattern returns OpenAPI path.
func (r Route) PathPattern() string {
	return r.pathPattern
}

// Args returns parsed arguments.
func (r Route) Args() []string {
	return r.args[:r.count]
}

// FindRoute finds Route for given method and path.
//
// Note: this method does not unescape path or handle reserved characters in path properly. Use FindPath instead.
func (s *Server) FindRoute(method, path string) (Route, bool) {
	return s.FindPath(method, &url.URL{Path: path})
}

// FindPath finds Route for given method and URL.
func (s *Server) FindPath(method string, u *url.URL) (r Route, _ bool) {
	var (
		elem = u.Path
		args = r.args
	)
	if rawPath := u.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
		}
		defer func() {
			for i, arg := range r.args[:r.count] {
				if unescaped, err := url.PathUnescape(arg); err == nil {
					r.args[i] = unescaped
				}
			}
		}()
	}

	elem, ok := s.cutPrefix(elem)
	if !ok {
		return r, false
	}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/api/"

			if l := len("/api/"); len(elem) >= l && elem[0:l] == "/api/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'a': // Prefix: "a"

				if l := len("a"); len(elem) >= l && elem[0:l] == "a" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'd': // Prefix: "dmin/"

					if l := len("dmin/"); len(elem) >= l && elem[0:l] == "dmin/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'a': // Prefix: "audit"

						if l := len("audit"); len(elem) >= l && elem[0:l] == "audit" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = AdminGetAuditLogOperation
								r.summary = "Admin — paginated audit log"
								r.operationID = "adminGetAuditLog"
								r.operationGroup = ""
								r.pathPattern = "/api/admin/audit"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

					case 'c': // Prefix: "calendars"

						if l := len("calendars"); len(elem) >= l && elem[0:l] == "calendars" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = AdminListCalendarsOperation
								r.summary = "Admin — list all calendars across all users"
								r.operationID = "adminListCalendars"
								r.operationGroup = ""
								r.pathPattern = "/api/admin/calendars"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

					case 'd': // Prefix: "devices"

						if l := len("devices"); len(elem) >= l && elem[0:l] == "devices" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = AdminListDevicesOperation
								r.summary = "Admin — list all devices across all users"
								r.operationID = "adminListDevices"
								r.operationGroup = ""
								r.pathPattern = "/api/admin/devices"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

					case 'g': // Prefix: "geofences"

						if l := len("geofences"); len(elem) >= l && elem[0:l] == "geofences" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = AdminListGeofencesOperation
								r.summary = "Admin — list all geofences across all users"
								r.operationID = "adminListGeofences"
								r.operationGroup = ""
								r.pathPattern = "/api/admin/geofences"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

					case 'n': // Prefix: "notifications"

						if l := len("notifications"); len(elem) >= l && elem[0:l] == "notifications" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = AdminListNotificationsOperation
								r.summary = "Admin — list all notification rules across all users"
								r.operationID = "adminListNotifications"
								r.operationGroup = ""
								r.pathPattern = "/api/admin/notifications"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

					case 'p': // Prefix: "positions"

						if l := len("positions"); len(elem) >= l && elem[0:l] == "positions" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = AdminListPositionsOperation
								r.summary = "Admin — list all latest positions across all devices"
								r.operationID = "adminListPositions"
								r.operationGroup = ""
								r.pathPattern = "/api/admin/positions"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

					case 's': // Prefix: "s"

						if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 't': // Prefix: "tatistics"

							if l := len("tatistics"); len(elem) >= l && elem[0:l] == "tatistics" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch method {
								case "GET":
									r.name = AdminGetStatisticsOperation
									r.summary = "Admin — platform-wide statistics"
									r.operationID = "adminGetStatistics"
									r.operationGroup = ""
									r.pathPattern = "/api/admin/statistics"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}
							switch elem[0] {
							case '/': // Prefix: "/users/"

								if l := len("/users/"); len(elem) >= l && elem[0:l] == "/users/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "id"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[0] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "GET":
										r.name = AdminGetUserStatisticsOperation
										r.summary = "Admin — statistics for a specific user"
										r.operationID = "adminGetUserStatistics"
										r.operationGroup = ""
										r.pathPattern = "/api/admin/statistics/users/{id}"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							}

						case 'u': // Prefix: "udo"

							if l := len("udo"); len(elem) >= l && elem[0:l] == "udo" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch method {
								case "DELETE":
									r.name = EndSudoOperation
									r.summary = "End sudo/impersonation session"
									r.operationID = "endSudo"
									r.operationGroup = ""
									r.pathPattern = "/api/admin/sudo"
									r.args = args
									r.count = 0
									return r, true
								case "GET":
									r.name = GetSudoStatusOperation
									r.summary = "Get current sudo/impersonation status"
									r.operationID = "getSudoStatus"
									r.operationGroup = ""
									r.pathPattern = "/api/admin/sudo"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "id"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[0] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "POST":
										r.name = AdminStartSudoOperation
										r.summary = "Admin — start impersonating a user"
										r.operationID = "adminStartSudo"
										r.operationGroup = ""
										r.pathPattern = "/api/admin/sudo/{id}"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							}

						}

					}

				case 'u': // Prefix: "uth/oidc/"

					if l := len("uth/oidc/"); len(elem) >= l && elem[0:l] == "uth/oidc/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'c': // Prefix: "c"

						if l := len("c"); len(elem) >= l && elem[0:l] == "c" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'a': // Prefix: "allback"

							if l := len("allback"); len(elem) >= l && elem[0:l] == "allback" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = OidcCallbackOperation
									r.summary = "OIDC callback after provider authentication"
									r.operationID = "oidcCallback"
									r.operationGroup = ""
									r.pathPattern = "/api/auth/oidc/callback"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

						case 'o': // Prefix: "onfig"

							if l := len("onfig"); len(elem) >= l && elem[0:l] == "onfig" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = GetOIDCConfigOperation
									r.summary = "Get OIDC configuration (enabled/disabled)"
									r.operationID = "getOIDCConfig"
									r.operationGroup = ""
									r.pathPattern = "/api/auth/oidc/config"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

						}

					case 'l': // Prefix: "login"

						if l := len("login"); len(elem) >= l && elem[0:l] == "login" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = OidcLoginOperation
								r.summary = "Initiate OIDC login flow (redirects to provider)"
								r.operationID = "oidcLogin"
								r.operationGroup = ""
								r.pathPattern = "/api/auth/oidc/login"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

					}

				}

			case 'c': // Prefix: "c"

				if l := len("c"); len(elem) >= l && elem[0:l] == "c" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'a': // Prefix: "alendars"

					if l := len("alendars"); len(elem) >= l && elem[0:l] == "alendars" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch method {
						case "GET":
							r.name = ListCalendarsOperation
							r.summary = "List calendars for the authenticated user"
							r.operationID = "listCalendars"
							r.operationGroup = ""
							r.pathPattern = "/api/calendars"
							r.args = args
							r.count = 0
							return r, true
						case "POST":
							r.name = CreateCalendarOperation
							r.summary = "Create a calendar"
							r.operationID = "createCalendar"
							r.operationGroup = ""
							r.pathPattern = "/api/calendars"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "id"
						// Match until "/"
						idx := strings.IndexByte(elem, '/')
						if idx < 0 {
							idx = len(elem)
						}
						args[0] = elem[:idx]
						elem = elem[idx:]

						if len(elem) == 0 {
							switch method {
							case "DELETE":
								r.name = DeleteCalendarOperation
								r.summary = "Delete a calendar"
								r.operationID = "deleteCalendar"
								r.operationGroup = ""
								r.pathPattern = "/api/calendars/{id}"
								r.args = args
								r.count = 1
								return r, true
							case "PUT":
								r.name = UpdateCalendarOperation
								r.summary = "Update a calendar"
								r.operationID = "updateCalendar"
								r.operationGroup = ""
								r.pathPattern = "/api/calendars/{id}"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}
						switch elem[0] {
						case '/': // Prefix: "/check"

							if l := len("/check"); len(elem) >= l && elem[0:l] == "/check" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = CheckCalendarOperation
									r.summary = "Check if a calendar is currently active"
									r.operationID = "checkCalendar"
									r.operationGroup = ""
									r.pathPattern = "/api/calendars/{id}/check"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						}

					}

				case 'o': // Prefix: "ommands"

					if l := len("ommands"); len(elem) >= l && elem[0:l] == "ommands" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch method {
						case "GET":
							r.name = ListCommandsOperation
							r.summary = "List saved commands"
							r.operationID = "listCommands"
							r.operationGroup = ""
							r.pathPattern = "/api/commands"
							r.args = args
							r.count = 0
							return r, true
						case "POST":
							r.name = CreateCommandOperation
							r.summary = "Save a command (not yet sent)"
							r.operationID = "createCommand"
							r.operationGroup = ""
							r.pathPattern = "/api/commands"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 's': // Prefix: "send"

							if l := len("send"); len(elem) >= l && elem[0:l] == "send" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = SendCommandOperation
									r.summary = "Send a command to a device immediately"
									r.operationID = "sendCommand"
									r.operationGroup = ""
									r.pathPattern = "/api/commands/send"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

						case 't': // Prefix: "types"

							if l := len("types"); len(elem) >= l && elem[0:l] == "types" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = GetCommandTypesOperation
									r.summary = "List supported command types"
									r.operationID = "getCommandTypes"
									r.operationGroup = ""
									r.pathPattern = "/api/commands/types"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

						}

					}

				}

			case 'd': // Prefix: "devices"

				if l := len("devices"); len(elem) >= l && elem[0:l] == "devices" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "GET":
						r.name = ListDevicesOperation
						r.summary = "List devices for the authenticated user"
						r.operationID = "listDevices"
						r.operationGroup = ""
						r.pathPattern = "/api/devices"
						r.args = args
						r.count = 0
						return r, true
					case "POST":
						r.name = CreateDeviceOperation
						r.summary = "Create a device"
						r.operationID = "createDevice"
						r.operationGroup = ""
						r.pathPattern = "/api/devices"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "id"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch method {
						case "DELETE":
							r.name = DeleteDeviceOperation
							r.summary = "Delete a device"
							r.operationID = "deleteDevice"
							r.operationGroup = ""
							r.pathPattern = "/api/devices/{id}"
							r.args = args
							r.count = 1
							return r, true
						case "GET":
							r.name = GetDeviceOperation
							r.summary = "Get a device by ID"
							r.operationID = "getDevice"
							r.operationGroup = ""
							r.pathPattern = "/api/devices/{id}"
							r.args = args
							r.count = 1
							return r, true
						case "PUT":
							r.name = UpdateDeviceOperation
							r.summary = "Update a device"
							r.operationID = "updateDevice"
							r.operationGroup = ""
							r.pathPattern = "/api/devices/{id}"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'g': // Prefix: "gpx"

							if l := len("gpx"); len(elem) >= l && elem[0:l] == "gpx" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = ImportGPXOperation
									r.summary = "Import GPX track for a device"
									r.operationID = "importGPX"
									r.operationGroup = ""
									r.pathPattern = "/api/devices/{id}/gpx"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						case 's': // Prefix: "share"

							if l := len("share"); len(elem) >= l && elem[0:l] == "share" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch method {
								case "POST":
									r.name = CreateShareOperation
									r.summary = "Create a public share link for a device"
									r.operationID = "createShare"
									r.operationGroup = ""
									r.pathPattern = "/api/devices/{id}/share"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}
							switch elem[0] {
							case 's': // Prefix: "s"

								if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "GET":
										r.name = ListSharesOperation
										r.summary = "List share links for a device"
										r.operationID = "listShares"
										r.operationGroup = ""
										r.pathPattern = "/api/devices/{id}/shares"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							}

						}

					}

				}

			case 'e': // Prefix: "events"

				if l := len("events"); len(elem) >= l && elem[0:l] == "events" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "GET":
						r.name = ListEventsOperation
						r.summary = "List events for the authenticated user's devices"
						r.operationID = "listEvents"
						r.operationGroup = ""
						r.pathPattern = "/api/events"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

			case 'g': // Prefix: "geofences"

				if l := len("geofences"); len(elem) >= l && elem[0:l] == "geofences" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "GET":
						r.name = ListGeofencesOperation
						r.summary = "List geofences for the authenticated user"
						r.operationID = "listGeofences"
						r.operationGroup = ""
						r.pathPattern = "/api/geofences"
						r.args = args
						r.count = 0
						return r, true
					case "POST":
						r.name = CreateGeofenceOperation
						r.summary = "Create a geofence"
						r.operationID = "createGeofence"
						r.operationGroup = ""
						r.pathPattern = "/api/geofences"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "id"
					// Leaf parameter, slashes are prohibited
					idx := strings.IndexByte(elem, '/')
					if idx >= 0 {
						break
					}
					args[0] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "DELETE":
							r.name = DeleteGeofenceOperation
							r.summary = "Delete a geofence"
							r.operationID = "deleteGeofence"
							r.operationGroup = ""
							r.pathPattern = "/api/geofences/{id}"
							r.args = args
							r.count = 1
							return r, true
						case "GET":
							r.name = GetGeofenceOperation
							r.summary = "Get a geofence by ID"
							r.operationID = "getGeofence"
							r.operationGroup = ""
							r.pathPattern = "/api/geofences/{id}"
							r.args = args
							r.count = 1
							return r, true
						case "PUT":
							r.name = UpdateGeofenceOperation
							r.summary = "Update a geofence"
							r.operationID = "updateGeofence"
							r.operationGroup = ""
							r.pathPattern = "/api/geofences/{id}"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}

				}

			case 'h': // Prefix: "health"

				if l := len("health"); len(elem) >= l && elem[0:l] == "health" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "GET":
						r.name = GetHealthOperation
						r.summary = "Health check"
						r.operationID = "getHealth"
						r.operationGroup = ""
						r.pathPattern = "/api/health"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

			case 'k': // Prefix: "keys"

				if l := len("keys"); len(elem) >= l && elem[0:l] == "keys" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "GET":
						r.name = ListApiKeysOperation
						r.summary = "List API keys for the authenticated user"
						r.operationID = "listApiKeys"
						r.operationGroup = ""
						r.pathPattern = "/api/keys"
						r.args = args
						r.count = 0
						return r, true
					case "POST":
						r.name = CreateApiKeyOperation
						r.summary = "Create an API key"
						r.operationID = "createApiKey"
						r.operationGroup = ""
						r.pathPattern = "/api/keys"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "id"
					// Leaf parameter, slashes are prohibited
					idx := strings.IndexByte(elem, '/')
					if idx >= 0 {
						break
					}
					args[0] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "DELETE":
							r.name = DeleteApiKeyOperation
							r.summary = "Delete an API key"
							r.operationID = "deleteApiKey"
							r.operationGroup = ""
							r.pathPattern = "/api/keys/{id}"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}

				}

			case 'n': // Prefix: "notifications"

				if l := len("notifications"); len(elem) >= l && elem[0:l] == "notifications" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "GET":
						r.name = ListNotificationsOperation
						r.summary = "List notification rules for the authenticated user"
						r.operationID = "listNotifications"
						r.operationGroup = ""
						r.pathPattern = "/api/notifications"
						r.args = args
						r.count = 0
						return r, true
					case "POST":
						r.name = CreateNotificationOperation
						r.summary = "Create a notification rule"
						r.operationID = "createNotification"
						r.operationGroup = ""
						r.pathPattern = "/api/notifications"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "id"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch method {
						case "DELETE":
							r.name = DeleteNotificationOperation
							r.summary = "Delete a notification rule"
							r.operationID = "deleteNotification"
							r.operationGroup = ""
							r.pathPattern = "/api/notifications/{id}"
							r.args = args
							r.count = 1
							return r, true
						case "PUT":
							r.name = UpdateNotificationOperation
							r.summary = "Update a notification rule"
							r.operationID = "updateNotification"
							r.operationGroup = ""
							r.pathPattern = "/api/notifications/{id}"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'l': // Prefix: "logs"

							if l := len("logs"); len(elem) >= l && elem[0:l] == "logs" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = NotificationLogsOperation
									r.summary = "Get delivery logs for a notification rule"
									r.operationID = "notificationLogs"
									r.operationGroup = ""
									r.pathPattern = "/api/notifications/{id}/logs"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						case 't': // Prefix: "test"

							if l := len("test"); len(elem) >= l && elem[0:l] == "test" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = TestNotificationOperation
									r.summary = "Send a test notification"
									r.operationID = "testNotification"
									r.operationGroup = ""
									r.pathPattern = "/api/notifications/{id}/test"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						}

					}

				}

			case 'p': // Prefix: "p"

				if l := len("p"); len(elem) >= l && elem[0:l] == "p" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'o': // Prefix: "ositions"

					if l := len("ositions"); len(elem) >= l && elem[0:l] == "ositions" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = GetPositionsOperation
							r.summary = "Get positions for devices"
							r.operationID = "getPositions"
							r.operationGroup = ""
							r.pathPattern = "/api/positions"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

				case 'r': // Prefix: "rofile"

					if l := len("rofile"); len(elem) >= l && elem[0:l] == "rofile" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "PUT":
							r.name = UpdateProfileOperation
							r.summary = "Update the authenticated user's own profile"
							r.operationID = "updateProfile"
							r.operationGroup = ""
							r.pathPattern = "/api/profile"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

				}

			case 'r': // Prefix: "reports/events"

				if l := len("reports/events"); len(elem) >= l && elem[0:l] == "reports/events" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "GET":
						r.name = ReportEventsOperation
						r.summary = "Report events in a time range (same as listEvents, Traccar-compatible path)"
						r.operationID = "reportEvents"
						r.operationGroup = ""
						r.pathPattern = "/api/reports/events"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

			case 's': // Prefix: "s"

				if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'e': // Prefix: "e"

					if l := len("e"); len(elem) >= l && elem[0:l] == "e" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'r': // Prefix: "rver"

						if l := len("rver"); len(elem) >= l && elem[0:l] == "rver" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = GetServerOperation
								r.summary = "Traccar-compatible server info"
								r.operationID = "getServer"
								r.operationGroup = ""
								r.pathPattern = "/api/server"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

					case 's': // Prefix: "ssion"

						if l := len("ssion"); len(elem) >= l && elem[0:l] == "ssion" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch method {
							case "DELETE":
								r.name = LogoutOperation
								r.summary = "Logout (delete current session)"
								r.operationID = "logout"
								r.operationGroup = ""
								r.pathPattern = "/api/session"
								r.args = args
								r.count = 0
								return r, true
							case "GET":
								r.name = GetSessionOperation
								r.summary = "Get current session / validate credentials"
								r.operationID = "getSession"
								r.operationGroup = ""
								r.pathPattern = "/api/session"
								r.args = args
								r.count = 0
								return r, true
							case "POST":
								r.name = LoginOperation
								r.summary = "Login with email + password"
								r.operationID = "login"
								r.operationGroup = ""
								r.pathPattern = "/api/session"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}
						switch elem[0] {
						case '/': // Prefix: "/token"

							if l := len("/token"); len(elem) >= l && elem[0:l] == "/token" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = GenerateTokenOperation
									r.summary = "Generate a long-lived API token for the current session"
									r.operationID = "generateToken"
									r.operationGroup = ""
									r.pathPattern = "/api/session/token"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

						case 's': // Prefix: "s"

							if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch method {
								case "DELETE":
									r.name = LogoutAllOperation
									r.summary = "Revoke all sessions for the authenticated user"
									r.operationID = "logoutAll"
									r.operationGroup = ""
									r.pathPattern = "/api/sessions"
									r.args = args
									r.count = 0
									return r, true
								case "GET":
									r.name = ListSessionsOperation
									r.summary = "List active sessions for the authenticated user"
									r.operationID = "listSessions"
									r.operationGroup = ""
									r.pathPattern = "/api/sessions"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "id"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[0] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "DELETE":
										r.name = DeleteSessionOperation
										r.summary = "Revoke a specific session"
										r.operationID = "deleteSession"
										r.operationGroup = ""
										r.pathPattern = "/api/sessions/{id}"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							}

						}

					}

				case 'h': // Prefix: "hare"

					if l := len("hare"); len(elem) >= l && elem[0:l] == "hare" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "token"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[0] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = GetSharedDeviceOperation
								r.summary = "Get device info via public share token"
								r.operationID = "getSharedDevice"
								r.operationGroup = ""
								r.pathPattern = "/api/share/{token}"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}

					case 's': // Prefix: "s/"

						if l := len("s/"); len(elem) >= l && elem[0:l] == "s/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "id"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[0] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "DELETE":
								r.name = DeleteShareOperation
								r.summary = "Delete a share link"
								r.operationID = "deleteShare"
								r.operationGroup = ""
								r.pathPattern = "/api/shares/{id}"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}

					}

				}

			case 'u': // Prefix: "users"

				if l := len("users"); len(elem) >= l && elem[0:l] == "users" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "GET":
						r.name = AdminListUsersOperation
						r.summary = "Admin — list all users"
						r.operationID = "adminListUsers"
						r.operationGroup = ""
						r.pathPattern = "/api/users"
						r.args = args
						r.count = 0
						return r, true
					case "POST":
						r.name = AdminCreateUserOperation
						r.summary = "Admin — create a user"
						r.operationID = "adminCreateUser"
						r.operationGroup = ""
						r.pathPattern = "/api/users"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "id"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch method {
						case "DELETE":
							r.name = AdminDeleteUserOperation
							r.summary = "Admin — delete a user"
							r.operationID = "adminDeleteUser"
							r.operationGroup = ""
							r.pathPattern = "/api/users/{id}"
							r.args = args
							r.count = 1
							return r, true
						case "PUT":
							r.name = AdminUpdateUserOperation
							r.summary = "Admin — update a user"
							r.operationID = "adminUpdateUser"
							r.operationGroup = ""
							r.pathPattern = "/api/users/{id}"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'd': // Prefix: "devices"

							if l := len("devices"); len(elem) >= l && elem[0:l] == "devices" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch method {
								case "GET":
									r.name = AdminListUserDevicesOperation
									r.summary = "Admin — list all devices for a user"
									r.operationID = "adminListUserDevices"
									r.operationGroup = ""
									r.pathPattern = "/api/users/{id}/devices"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "deviceId"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[1] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "DELETE":
										r.name = AdminUnassignDeviceOperation
										r.summary = "Admin — unassign a device from a user"
										r.operationID = "adminUnassignDevice"
										r.operationGroup = ""
										r.pathPattern = "/api/users/{id}/devices/{deviceId}"
										r.args = args
										r.count = 2
										return r, true
									case "POST":
										r.name = AdminAssignDeviceOperation
										r.summary = "Admin — assign a device to a user"
										r.operationID = "adminAssignDevice"
										r.operationGroup = ""
										r.pathPattern = "/api/users/{id}/devices/{deviceId}"
										r.args = args
										r.count = 2
										return r, true
									default:
										return
									}
								}

							}

						case 'k': // Prefix: "keys"

							if l := len("keys"); len(elem) >= l && elem[0:l] == "keys" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = AdminListUserKeysOperation
									r.summary = "Admin — list API keys for a user"
									r.operationID = "adminListUserKeys"
									r.operationGroup = ""
									r.pathPattern = "/api/users/{id}/keys"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						case 's': // Prefix: "sessions/"

							if l := len("sessions/"); len(elem) >= l && elem[0:l] == "sessions/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "sessionId"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[1] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "DELETE":
									r.name = AdminDeleteUserSessionOperation
									r.summary = "Admin — revoke a specific session for a user"
									r.operationID = "adminDeleteUserSession"
									r.operationGroup = ""
									r.pathPattern = "/api/users/{id}/sessions/{sessionId}"
									r.args = args
									r.count = 2
									return r, true
								default:
									return
								}
							}

						}

					}

				}

			case 'v': // Prefix: "version"

				if l := len("version"); len(elem) >= l && elem[0:l] == "version" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "GET":
						r.name = GetVersionOperation
						r.summary = "Version info"
						r.operationID = "getVersion"
						r.operationGroup = ""
						r.pathPattern = "/api/version"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

			}

		}
	}
	return r, false
}
