// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// AdminAssignDevice implements adminAssignDevice operation.
	//
	// Admin — assign a device to a user.
	//
	// POST /api/users/{id}/devices/{deviceId}
	AdminAssignDevice(ctx context.Context, params AdminAssignDeviceParams) (AdminAssignDeviceRes, error)
	// AdminCreateUser implements adminCreateUser operation.
	//
	// Admin — create a user.
	//
	// POST /api/users
	AdminCreateUser(ctx context.Context, req *UserInput) (AdminCreateUserRes, error)
	// AdminDeleteUser implements adminDeleteUser operation.
	//
	// Admin — delete a user.
	//
	// DELETE /api/users/{id}
	AdminDeleteUser(ctx context.Context, params AdminDeleteUserParams) (AdminDeleteUserRes, error)
	// AdminDeleteUserSession implements adminDeleteUserSession operation.
	//
	// Admin — revoke a specific session for a user.
	//
	// DELETE /api/users/{id}/sessions/{sessionId}
	AdminDeleteUserSession(ctx context.Context, params AdminDeleteUserSessionParams) (AdminDeleteUserSessionRes, error)
	// AdminGetAuditLog implements adminGetAuditLog operation.
	//
	// Admin — paginated audit log.
	//
	// GET /api/admin/audit
	AdminGetAuditLog(ctx context.Context, params AdminGetAuditLogParams) (AdminGetAuditLogRes, error)
	// AdminGetStatistics implements adminGetStatistics operation.
	//
	// Admin — platform-wide statistics.
	//
	// GET /api/admin/statistics
	AdminGetStatistics(ctx context.Context) (AdminGetStatisticsRes, error)
	// AdminGetUserStatistics implements adminGetUserStatistics operation.
	//
	// Admin — statistics for a specific user.
	//
	// GET /api/admin/statistics/users/{id}
	AdminGetUserStatistics(ctx context.Context, params AdminGetUserStatisticsParams) (AdminGetUserStatisticsRes, error)
	// AdminListCalendars implements adminListCalendars operation.
	//
	// Admin — list all calendars across all users.
	//
	// GET /api/admin/calendars
	AdminListCalendars(ctx context.Context) (AdminListCalendarsRes, error)
	// AdminListDevices implements adminListDevices operation.
	//
	// Admin — list all devices across all users.
	//
	// GET /api/admin/devices
	AdminListDevices(ctx context.Context) (AdminListDevicesRes, error)
	// AdminListGeofences implements adminListGeofences operation.
	//
	// Admin — list all geofences across all users.
	//
	// GET /api/admin/geofences
	AdminListGeofences(ctx context.Context) (AdminListGeofencesRes, error)
	// AdminListNotifications implements adminListNotifications operation.
	//
	// Admin — list all notification rules across all users.
	//
	// GET /api/admin/notifications
	AdminListNotifications(ctx context.Context) (AdminListNotificationsRes, error)
	// AdminListPositions implements adminListPositions operation.
	//
	// Admin — list all latest positions across all devices.
	//
	// GET /api/admin/positions
	AdminListPositions(ctx context.Context) (AdminListPositionsRes, error)
	// AdminListUserDevices implements adminListUserDevices operation.
	//
	// Admin — list all devices for a user.
	//
	// GET /api/users/{id}/devices
	AdminListUserDevices(ctx context.Context, params AdminListUserDevicesParams) (AdminListUserDevicesRes, error)
	// AdminListUserKeys implements adminListUserKeys operation.
	//
	// Admin — list API keys for a user.
	//
	// GET /api/users/{id}/keys
	AdminListUserKeys(ctx context.Context, params AdminListUserKeysParams) (AdminListUserKeysRes, error)
	// AdminListUsers implements adminListUsers operation.
	//
	// Admin — list all users.
	//
	// GET /api/users
	AdminListUsers(ctx context.Context) (AdminListUsersRes, error)
	// AdminStartSudo implements adminStartSudo operation.
	//
	// Admin — start impersonating a user.
	//
	// POST /api/admin/sudo/{id}
	AdminStartSudo(ctx context.Context, params AdminStartSudoParams) (AdminStartSudoRes, error)
	// AdminUnassignDevice implements adminUnassignDevice operation.
	//
	// Admin — unassign a device from a user.
	//
	// DELETE /api/users/{id}/devices/{deviceId}
	AdminUnassignDevice(ctx context.Context, params AdminUnassignDeviceParams) (AdminUnassignDeviceRes, error)
	// AdminUpdateUser implements adminUpdateUser operation.
	//
	// Admin — update a user.
	//
	// PUT /api/users/{id}
	AdminUpdateUser(ctx context.Context, req *UserInput, params AdminUpdateUserParams) (AdminUpdateUserRes, error)
	// CheckCalendar implements checkCalendar operation.
	//
	// Check if a calendar is currently active.
	//
	// GET /api/calendars/{id}/check
	CheckCalendar(ctx context.Context, params CheckCalendarParams) (CheckCalendarRes, error)
	// CreateApiKey implements createApiKey operation.
	//
	// Create an API key.
	//
	// POST /api/keys
	CreateApiKey(ctx context.Context, req *ApiKeyInput) (CreateApiKeyRes, error)
	// CreateCalendar implements createCalendar operation.
	//
	// Create a calendar.
	//
	// POST /api/calendars
	CreateCalendar(ctx context.Context, req *CalendarInput) (CreateCalendarRes, error)
	// CreateCommand implements createCommand operation.
	//
	// Save a command (not yet sent).
	//
	// POST /api/commands
	CreateCommand(ctx context.Context, req *CommandInput) (CreateCommandRes, error)
	// CreateDevice implements createDevice operation.
	//
	// Create a device.
	//
	// POST /api/devices
	CreateDevice(ctx context.Context, req *DeviceInput) (CreateDeviceRes, error)
	// CreateGeofence implements createGeofence operation.
	//
	// Create a geofence.
	//
	// POST /api/geofences
	CreateGeofence(ctx context.Context, req *GeofenceInput) (CreateGeofenceRes, error)
	// CreateNotification implements createNotification operation.
	//
	// Create a notification rule.
	//
	// POST /api/notifications
	CreateNotification(ctx context.Context, req *NotificationRuleInput) (CreateNotificationRes, error)
	// CreateShare implements createShare operation.
	//
	// Create a public share link for a device.
	//
	// POST /api/devices/{id}/share
	CreateShare(ctx context.Context, req OptCreateShareRequest, params CreateShareParams) (CreateShareRes, error)
	// DeleteApiKey implements deleteApiKey operation.
	//
	// Delete an API key.
	//
	// DELETE /api/keys/{id}
	DeleteApiKey(ctx context.Context, params DeleteApiKeyParams) (DeleteApiKeyRes, error)
	// DeleteCalendar implements deleteCalendar operation.
	//
	// Delete a calendar.
	//
	// DELETE /api/calendars/{id}
	DeleteCalendar(ctx context.Context, params DeleteCalendarParams) (DeleteCalendarRes, error)
	// DeleteDevice implements deleteDevice operation.
	//
	// Delete a device.
	//
	// DELETE /api/devices/{id}
	DeleteDevice(ctx context.Context, params DeleteDeviceParams) (DeleteDeviceRes, error)
	// DeleteGeofence implements deleteGeofence operation.
	//
	// Delete a geofence.
	//
	// DELETE /api/geofences/{id}
	DeleteGeofence(ctx context.Context, params DeleteGeofenceParams) (DeleteGeofenceRes, error)
	// DeleteNotification implements deleteNotification operation.
	//
	// Delete a notification rule.
	//
	// DELETE /api/notifications/{id}
	DeleteNotification(ctx context.Context, params DeleteNotificationParams) (DeleteNotificationRes, error)
	// DeleteSession implements deleteSession operation.
	//
	// Revoke a specific session.
	//
	// DELETE /api/sessions/{id}
	DeleteSession(ctx context.Context, params DeleteSessionParams) (DeleteSessionRes, error)
	// DeleteShare implements deleteShare operation.
	//
	// Delete a share link.
	//
	// DELETE /api/shares/{id}
	DeleteShare(ctx context.Context, params DeleteShareParams) (DeleteShareRes, error)
	// EndSudo implements endSudo operation.
	//
	// End sudo/impersonation session.
	//
	// DELETE /api/admin/sudo
	EndSudo(ctx context.Context) (EndSudoRes, error)
	// GenerateToken implements generateToken operation.
	//
	// Generate a long-lived API token for the current session.
	//
	// POST /api/session/token
	GenerateToken(ctx context.Context) (GenerateTokenRes, error)
	// GetCommandTypes implements getCommandTypes operation.
	//
	// List supported command types.
	//
	// GET /api/commands/types
	GetCommandTypes(ctx context.Context) (GetCommandTypesRes, error)
	// GetDevice implements getDevice operation.
	//
	// Get a device by ID.
	//
	// GET /api/devices/{id}
	GetDevice(ctx context.Context, params GetDeviceParams) (GetDeviceRes, error)
	// GetGeofence implements getGeofence operation.
	//
	// Get a geofence by ID.
	//
	// GET /api/geofences/{id}
	GetGeofence(ctx context.Context, params GetGeofenceParams) (GetGeofenceRes, error)
	// GetHealth implements getHealth operation.
	//
	// Health check.
	//
	// GET /api/health
	GetHealth(ctx context.Context) (*GetHealthOK, error)
	// GetOIDCConfig implements getOIDCConfig operation.
	//
	// Get OIDC configuration (enabled/disabled).
	//
	// GET /api/auth/oidc/config
	GetOIDCConfig(ctx context.Context) (*OIDCConfig, error)
	// GetPositions implements getPositions operation.
	//
	// Get positions for devices.
	//
	// GET /api/positions
	GetPositions(ctx context.Context, params GetPositionsParams) (GetPositionsRes, error)
	// GetServer implements getServer operation.
	//
	// Traccar-compatible server info.
	//
	// GET /api/server
	GetServer(ctx context.Context) (*ServerInfo, error)
	// GetSession implements getSession operation.
	//
	// Get current session / validate credentials.
	//
	// GET /api/session
	GetSession(ctx context.Context) (GetSessionRes, error)
	// GetSharedDevice implements getSharedDevice operation.
	//
	// Get device info via public share token.
	//
	// GET /api/share/{token}
	GetSharedDevice(ctx context.Context, params GetSharedDeviceParams) (GetSharedDeviceRes, error)
	// GetSudoStatus implements getSudoStatus operation.
	//
	// Get current sudo/impersonation status.
	//
	// GET /api/admin/sudo
	GetSudoStatus(ctx context.Context) (GetSudoStatusRes, error)
	// GetVersion implements getVersion operation.
	//
	// Version info.
	//
	// GET /api/version
	GetVersion(ctx context.Context) (*VersionInfo, error)
	// ImportGPX implements importGPX operation.
	//
	// Import GPX track for a device.
	//
	// POST /api/devices/{id}/gpx
	ImportGPX(ctx context.Context, req ImportGPXReq, params ImportGPXParams) (ImportGPXRes, error)
	// ListApiKeys implements listApiKeys operation.
	//
	// List API keys for the authenticated user.
	//
	// GET /api/keys
	ListApiKeys(ctx context.Context) (ListApiKeysRes, error)
	// ListCalendars implements listCalendars operation.
	//
	// List calendars for the authenticated user.
	//
	// GET /api/calendars
	ListCalendars(ctx context.Context) (ListCalendarsRes, error)
	// ListCommands implements listCommands operation.
	//
	// List saved commands.
	//
	// GET /api/commands
	ListCommands(ctx context.Context, params ListCommandsParams) (ListCommandsRes, error)
	// ListDevices implements listDevices operation.
	//
	// List devices for the authenticated user.
	//
	// GET /api/devices
	ListDevices(ctx context.Context) (ListDevicesRes, error)
	// ListEvents implements listEvents operation.
	//
	// List events for the authenticated user's devices.
	//
	// GET /api/events
	ListEvents(ctx context.Context, params ListEventsParams) (ListEventsRes, error)
	// ListGeofences implements listGeofences operation.
	//
	// List geofences for the authenticated user.
	//
	// GET /api/geofences
	ListGeofences(ctx context.Context) (ListGeofencesRes, error)
	// ListNotifications implements listNotifications operation.
	//
	// List notification rules for the authenticated user.
	//
	// GET /api/notifications
	ListNotifications(ctx context.Context) (ListNotificationsRes, error)
	// ListSessions implements listSessions operation.
	//
	// List active sessions for the authenticated user.
	//
	// GET /api/sessions
	ListSessions(ctx context.Context) (ListSessionsRes, error)
	// ListShares implements listShares operation.
	//
	// List share links for a device.
	//
	// GET /api/devices/{id}/shares
	ListShares(ctx context.Context, params ListSharesParams) (ListSharesRes, error)
	// Login implements login operation.
	//
	// Login with email + password.
	//
	// POST /api/session
	Login(ctx context.Context, req *LoginRequest) (LoginRes, error)
	// Logout implements logout operation.
	//
	// Logout (delete current session).
	//
	// DELETE /api/session
	Logout(ctx context.Context) (LogoutRes, error)
	// LogoutAll implements logoutAll operation.
	//
	// Revoke all sessions for the authenticated user.
	//
	// DELETE /api/sessions
	LogoutAll(ctx context.Context) (LogoutAllRes, error)
	// NotificationLogs implements notificationLogs operation.
	//
	// Get delivery logs for a notification rule.
	//
	// GET /api/notifications/{id}/logs
	NotificationLogs(ctx context.Context, params NotificationLogsParams) (NotificationLogsRes, error)
	// OidcCallback implements oidcCallback operation.
	//
	// OIDC callback after provider authentication.
	//
	// GET /api/auth/oidc/callback
	OidcCallback(ctx context.Context, params OidcCallbackParams) (OidcCallbackRes, error)
	// OidcLogin implements oidcLogin operation.
	//
	// Initiate OIDC login flow (redirects to provider).
	//
	// GET /api/auth/oidc/login
	OidcLogin(ctx context.Context) error
	// ReportEvents implements reportEvents operation.
	//
	// Report events in a time range (same as listEvents, Traccar-compatible path).
	//
	// GET /api/reports/events
	ReportEvents(ctx context.Context, params ReportEventsParams) (ReportEventsRes, error)
	// SendCommand implements sendCommand operation.
	//
	// Send a command to a device immediately.
	//
	// POST /api/commands/send
	SendCommand(ctx context.Context, req *SendCommandRequest) (SendCommandRes, error)
	// TestNotification implements testNotification operation.
	//
	// Send a test notification.
	//
	// POST /api/notifications/{id}/test
	TestNotification(ctx context.Context, params TestNotificationParams) (TestNotificationRes, error)
	// UpdateCalendar implements updateCalendar operation.
	//
	// Update a calendar.
	//
	// PUT /api/calendars/{id}
	UpdateCalendar(ctx context.Context, req *CalendarInput, params UpdateCalendarParams) (UpdateCalendarRes, error)
	// UpdateDevice implements updateDevice operation.
	//
	// Update a device.
	//
	// PUT /api/devices/{id}
	UpdateDevice(ctx context.Context, req *DeviceInput, params UpdateDeviceParams) (UpdateDeviceRes, error)
	// UpdateGeofence implements updateGeofence operation.
	//
	// Update a geofence.
	//
	// PUT /api/geofences/{id}
	UpdateGeofence(ctx context.Context, req *GeofenceUpdateInput, params UpdateGeofenceParams) (UpdateGeofenceRes, error)
	// UpdateNotification implements updateNotification operation.
	//
	// Update a notification rule.
	//
	// PUT /api/notifications/{id}
	UpdateNotification(ctx context.Context, req *NotificationRuleInput, params UpdateNotificationParams) (UpdateNotificationRes, error)
	// UpdateProfile implements updateProfile operation.
	//
	// Update the authenticated user's own profile.
	//
	// PUT /api/profile
	UpdateProfile(ctx context.Context, req *UpdateProfileRequest) (UpdateProfileRes, error)
	// NewError creates *UnexpectedErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *UnexpectedErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
