// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleBearerAuth handles bearerAuth security.
	// API key token.
	HandleBearerAuth(ctx context.Context, operationName OperationName, t BearerAuth) (context.Context, error)
	// HandleCookieAuth handles cookieAuth security.
	// Session cookie set after login.
	HandleCookieAuth(ctx context.Context, operationName OperationName, t CookieAuth) (context.Context, error)
	// HandleXAuthToken handles xAuthToken security.
	// IOS PWA fallback — pass session_id value here.
	HandleXAuthToken(ctx context.Context, operationName OperationName, t XAuthToken) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

// operationRolesBearerAuth is a private map storing roles per operation.
var operationRolesBearerAuth = map[string][]string{
	AdminAssignDeviceOperation:      []string{},
	AdminCreateUserOperation:        []string{},
	AdminDeleteUserOperation:        []string{},
	AdminDeleteUserSessionOperation: []string{},
	AdminGetAuditLogOperation:       []string{},
	AdminGetStatisticsOperation:     []string{},
	AdminGetUserStatisticsOperation: []string{},
	AdminListCalendarsOperation:     []string{},
	AdminListDevicesOperation:       []string{},
	AdminListGeofencesOperation:     []string{},
	AdminListNotificationsOperation: []string{},
	AdminListPositionsOperation:     []string{},
	AdminListUserDevicesOperation:   []string{},
	AdminListUserKeysOperation:      []string{},
	AdminListUsersOperation:         []string{},
	AdminStartSudoOperation:         []string{},
	AdminUnassignDeviceOperation:    []string{},
	AdminUpdateUserOperation:        []string{},
	CheckCalendarOperation:          []string{},
	CreateApiKeyOperation:           []string{},
	CreateCalendarOperation:         []string{},
	CreateCommandOperation:          []string{},
	CreateDeviceOperation:           []string{},
	CreateGeofenceOperation:         []string{},
	CreateNotificationOperation:     []string{},
	CreateShareOperation:            []string{},
	DeleteApiKeyOperation:           []string{},
	DeleteCalendarOperation:         []string{},
	DeleteDeviceOperation:           []string{},
	DeleteGeofenceOperation:         []string{},
	DeleteNotificationOperation:     []string{},
	DeletePasskeyOperation:          []string{},
	DeleteSessionOperation:          []string{},
	DeleteShareOperation:            []string{},
	EndSudoOperation:                []string{},
	GenerateTokenOperation:          []string{},
	GetCommandTypesOperation:        []string{},
	GetDeviceOperation:              []string{},
	GetGeofenceOperation:            []string{},
	GetPositionsOperation:           []string{},
	GetSessionOperation:             []string{},
	GetSudoStatusOperation:          []string{},
	ImportGPXOperation:              []string{},
	ListApiKeysOperation:            []string{},
	ListCalendarsOperation:          []string{},
	ListCommandsOperation:           []string{},
	ListDevicesOperation:            []string{},
	ListEventsOperation:             []string{},
	ListGeofencesOperation:          []string{},
	ListNotificationsOperation:      []string{},
	ListPasskeysOperation:           []string{},
	ListSessionsOperation:           []string{},
	ListSharesOperation:             []string{},
	LogoutOperation:                 []string{},
	LogoutAllOperation:              []string{},
	NotificationLogsOperation:       []string{},
	PasskeyRegisterBeginOperation:   []string{},
	PasskeyRegisterFinishOperation:  []string{},
	ReportEventsOperation:           []string{},
	SendCommandOperation:            []string{},
	TestNotificationOperation:       []string{},
	UpdateCalendarOperation:         []string{},
	UpdateDeviceOperation:           []string{},
	UpdateGeofenceOperation:         []string{},
	UpdateNotificationOperation:     []string{},
	UpdateProfileOperation:          []string{},
}

// GetRolesForBearerAuth returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForBearerAuth(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForBearerAuth(operation string) []string {
	roles, ok := operationRolesBearerAuth[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

// operationRolesCookieAuth is a private map storing roles per operation.
var operationRolesCookieAuth = map[string][]string{
	AdminAssignDeviceOperation:      []string{},
	AdminCreateUserOperation:        []string{},
	AdminDeleteUserOperation:        []string{},
	AdminDeleteUserSessionOperation: []string{},
	AdminGetAuditLogOperation:       []string{},
	AdminGetStatisticsOperation:     []string{},
	AdminGetUserStatisticsOperation: []string{},
	AdminListCalendarsOperation:     []string{},
	AdminListDevicesOperation:       []string{},
	AdminListGeofencesOperation:     []string{},
	AdminListNotificationsOperation: []string{},
	AdminListPositionsOperation:     []string{},
	AdminListUserDevicesOperation:   []string{},
	AdminListUserKeysOperation:      []string{},
	AdminListUsersOperation:         []string{},
	AdminStartSudoOperation:         []string{},
	AdminUnassignDeviceOperation:    []string{},
	AdminUpdateUserOperation:        []string{},
	CheckCalendarOperation:          []string{},
	CreateApiKeyOperation:           []string{},
	CreateCalendarOperation:         []string{},
	CreateCommandOperation:          []string{},
	CreateDeviceOperation:           []string{},
	CreateGeofenceOperation:         []string{},
	CreateNotificationOperation:     []string{},
	CreateShareOperation:            []string{},
	DeleteApiKeyOperation:           []string{},
	DeleteCalendarOperation:         []string{},
	DeleteDeviceOperation:           []string{},
	DeleteGeofenceOperation:         []string{},
	DeleteNotificationOperation:     []string{},
	DeletePasskeyOperation:          []string{},
	DeleteSessionOperation:          []string{},
	DeleteShareOperation:            []string{},
	EndSudoOperation:                []string{},
	GenerateTokenOperation:          []string{},
	GetCommandTypesOperation:        []string{},
	GetDeviceOperation:              []string{},
	GetGeofenceOperation:            []string{},
	GetPositionsOperation:           []string{},
	GetSessionOperation:             []string{},
	GetSudoStatusOperation:          []string{},
	ImportGPXOperation:              []string{},
	ListApiKeysOperation:            []string{},
	ListCalendarsOperation:          []string{},
	ListCommandsOperation:           []string{},
	ListDevicesOperation:            []string{},
	ListEventsOperation:             []string{},
	ListGeofencesOperation:          []string{},
	ListNotificationsOperation:      []string{},
	ListPasskeysOperation:           []string{},
	ListSessionsOperation:           []string{},
	ListSharesOperation:             []string{},
	LogoutOperation:                 []string{},
	LogoutAllOperation:              []string{},
	NotificationLogsOperation:       []string{},
	PasskeyRegisterBeginOperation:   []string{},
	PasskeyRegisterFinishOperation:  []string{},
	ReportEventsOperation:           []string{},
	SendCommandOperation:            []string{},
	TestNotificationOperation:       []string{},
	UpdateCalendarOperation:         []string{},
	UpdateDeviceOperation:           []string{},
	UpdateGeofenceOperation:         []string{},
	UpdateNotificationOperation:     []string{},
	UpdateProfileOperation:          []string{},
}

// GetRolesForCookieAuth returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForCookieAuth(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForCookieAuth(operation string) []string {
	roles, ok := operationRolesCookieAuth[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

// operationRolesXAuthToken is a private map storing roles per operation.
var operationRolesXAuthToken = map[string][]string{
	AdminAssignDeviceOperation:      []string{},
	AdminCreateUserOperation:        []string{},
	AdminDeleteUserOperation:        []string{},
	AdminDeleteUserSessionOperation: []string{},
	AdminGetAuditLogOperation:       []string{},
	AdminGetStatisticsOperation:     []string{},
	AdminGetUserStatisticsOperation: []string{},
	AdminListCalendarsOperation:     []string{},
	AdminListDevicesOperation:       []string{},
	AdminListGeofencesOperation:     []string{},
	AdminListNotificationsOperation: []string{},
	AdminListPositionsOperation:     []string{},
	AdminListUserDevicesOperation:   []string{},
	AdminListUserKeysOperation:      []string{},
	AdminListUsersOperation:         []string{},
	AdminStartSudoOperation:         []string{},
	AdminUnassignDeviceOperation:    []string{},
	AdminUpdateUserOperation:        []string{},
	CheckCalendarOperation:          []string{},
	CreateApiKeyOperation:           []string{},
	CreateCalendarOperation:         []string{},
	CreateCommandOperation:          []string{},
	CreateDeviceOperation:           []string{},
	CreateGeofenceOperation:         []string{},
	CreateNotificationOperation:     []string{},
	CreateShareOperation:            []string{},
	DeleteApiKeyOperation:           []string{},
	DeleteCalendarOperation:         []string{},
	DeleteDeviceOperation:           []string{},
	DeleteGeofenceOperation:         []string{},
	DeleteNotificationOperation:     []string{},
	DeletePasskeyOperation:          []string{},
	DeleteSessionOperation:          []string{},
	DeleteShareOperation:            []string{},
	EndSudoOperation:                []string{},
	GenerateTokenOperation:          []string{},
	GetCommandTypesOperation:        []string{},
	GetDeviceOperation:              []string{},
	GetGeofenceOperation:            []string{},
	GetPositionsOperation:           []string{},
	GetSessionOperation:             []string{},
	GetSudoStatusOperation:          []string{},
	ImportGPXOperation:              []string{},
	ListApiKeysOperation:            []string{},
	ListCalendarsOperation:          []string{},
	ListCommandsOperation:           []string{},
	ListDevicesOperation:            []string{},
	ListEventsOperation:             []string{},
	ListGeofencesOperation:          []string{},
	ListNotificationsOperation:      []string{},
	ListPasskeysOperation:           []string{},
	ListSessionsOperation:           []string{},
	ListSharesOperation:             []string{},
	LogoutOperation:                 []string{},
	LogoutAllOperation:              []string{},
	NotificationLogsOperation:       []string{},
	PasskeyRegisterBeginOperation:   []string{},
	PasskeyRegisterFinishOperation:  []string{},
	ReportEventsOperation:           []string{},
	SendCommandOperation:            []string{},
	TestNotificationOperation:       []string{},
	UpdateCalendarOperation:         []string{},
	UpdateDeviceOperation:           []string{},
	UpdateGeofenceOperation:         []string{},
	UpdateNotificationOperation:     []string{},
	UpdateProfileOperation:          []string{},
}

// GetRolesForXAuthToken returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForXAuthToken(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForXAuthToken(operation string) []string {
	roles, ok := operationRolesXAuthToken[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

func (s *Server) securityBearerAuth(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t BearerAuth
	token, ok := findAuthorization(req.Header, "Bearer")
	if !ok {
		return ctx, false, nil
	}
	t.Token = token
	t.Roles = operationRolesBearerAuth[operationName]
	rctx, err := s.sec.HandleBearerAuth(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

func (s *Server) securityCookieAuth(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t CookieAuth
	const parameterName = "session_id"
	var value string
	switch cookie, err := req.Cookie(parameterName); {
	case err == nil: // if NO error
		value = cookie.Value
	case errors.Is(err, http.ErrNoCookie):
		return ctx, false, nil
	default:
		return nil, false, errors.Wrap(err, "get cookie value")
	}
	t.APIKey = value
	t.Roles = operationRolesCookieAuth[operationName]
	rctx, err := s.sec.HandleCookieAuth(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

func (s *Server) securityXAuthToken(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t XAuthToken
	const parameterName = "X-Auth-Token"
	value := req.Header.Get(parameterName)
	if value == "" {
		return ctx, false, nil
	}
	t.APIKey = value
	t.Roles = operationRolesXAuthToken[operationName]
	rctx, err := s.sec.HandleXAuthToken(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// BearerAuth provides bearerAuth security value.
	// API key token.
	BearerAuth(ctx context.Context, operationName OperationName) (BearerAuth, error)
	// CookieAuth provides cookieAuth security value.
	// Session cookie set after login.
	CookieAuth(ctx context.Context, operationName OperationName) (CookieAuth, error)
	// XAuthToken provides xAuthToken security value.
	// IOS PWA fallback — pass session_id value here.
	XAuthToken(ctx context.Context, operationName OperationName) (XAuthToken, error)
}

func (s *Client) securityBearerAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.BearerAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"BearerAuth\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
func (s *Client) securityCookieAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.CookieAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"CookieAuth\"")
	}
	req.AddCookie(&http.Cookie{
		Name:  "session_id",
		Value: t.APIKey,
	})
	return nil
}
func (s *Client) securityXAuthToken(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.XAuthToken(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"XAuthToken\"")
	}
	req.Header.Set("X-Auth-Token", t.APIKey)
	return nil
}
