{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "motus.componentFullname" (list . "postgres") }}
  labels:
    {{- include "motus.componentLabels" (list . "database" "postgres") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: postgres
    protocol: TCP
    name: postgres
  selector:
    {{- include "motus.componentSelectorLabels" (list . "postgres") | nindent 4 }}
{{- end }}
