{{- if .Values.config.csrf.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "motus.fullname" . }}-csrf
  labels:
    {{- include "motus.labels" . | nindent 4 }}
type: Opaque
stringData:
  csrf-secret: {{ .Values.config.csrf.secret | quote }}
{{- end }}
